### ISSUE TITLE
Final project - Opening doors on rotated houses.

### ISSUE THREAD

**Issue by gCoccimiglio** [JRud52/3PercentMilk#10]
Currently opening doors works only for the houses that have not been rotated - I am clearly not correctly calculating the position of the door on the rotated houses. If anyone wants to look into this the rotation on the houses is 2 pi.

**Comment by xTVaser** [comment]
Radians are gross.
I'll look at it tomorrow. :+1:

**Comment by gCoccimiglio** [comment]
Fixed - as long as all houses are on the same straight road. The fix checks the rotation of the house and branches based on the rotation to correctly compute the position of the door, however it only has 2 possible paths 1 for rotated and 1 for not rotated - nothing in between.

**Comment by xTVaser** [comment]
#router rip v2
